Use burrito, bulma
platf0rm/platform-web-ui pull request #1
Opened 2017-03-27 12:52 UTC by Temoto-kun

Besides refreshing the libraries, the index page is reimplemented.

2017-03-27 13:21 UTC, eLoyyyyy approved these changes

2017-03-27 20:05 UTC, ghost requested changes
@Temoto-kun ignore empty css files generated by css-burrito

2017-03-28 01:52 UTC, Temoto-kun commented
@vkeusebio there is a good reason why I left the empty SCSS files there. It would be filled up later. I suggest we prune files in the long run.

2017-03-28 02:09 UTC, ghost approved these changes

2017-03-28 08:24 UTC, merged